f1 = int(input("enter students number 1 "))
f2 = int(input("enter students number 2 "))
f3 = int(input("enter students number 3 "))
f4 = int(input("enter students number 4 "))
f5 = int(input("enter students number 5  "))
f6 = int(input("enter students number 6 "))
f7 = int(input("enter students number 7 "))
students = [f1, f2, f3, f4, f5, f6, f7]
print(students)
students.sort()
print(stxxxxudents)
